import data_pop as pop

data_raw, m, n, objects, sources, ground_truth, n_mark = pop.Read()
print('data_raw')
print(data_raw)
print('m')
print(m)
print('n')
print(n)
print('objects')
print(objects)
print('objects size')
print(len(objects))
print('sources')
print(sources)
print('sources size')
print(len(sources))
print('ground_truth')
print(ground_truth)
print('ground_truth size')
print(len(ground_truth))
print('n_mark')
print(n_mark)
